"""
format_report.py — Turn committee_candidates.csv into a clean, complete Markdown
scaffold, ready to share back with Claude (or read directly) for narrative analysis.

WHY THIS EXISTS:
    committee_signals.py / screen_top_performers.py already produce a CSV with all
    the vote details, but a raw CSV loses nested detail (technical_details,
    quantitative_details, astrological_details are dict-like columns that get
    stringified awkwardly by pandas' default to_csv). This script expands those
    into a readable per-candidate Markdown section, so nothing gets lost when the
    file is shared for a narrative report.

    This is deliberately NOT an AI-generated narrative itself — it's a faithful,
    deterministic re-formatting of the numbers, so the narrative analysis (done by
    Claude, in chat, after this file is shared) is always grounded in the exact
    computed data, not a paraphrase of a paraphrase.

INPUT: runs/committee_candidates.csv (from committee_signals.py or
       screen_top_performers.py)
OUTPUT: runs/committee_report.md

Run:
    python src/format_report.py
"""

from __future__ import annotations

import ast
from pathlib import Path

import pandas as pd

INPUT_CSV = Path("runs/committee_candidates.csv")
OUTPUT_MD = Path("runs/committee_report.md")


def safe_parse_dict(value) -> dict:
    """
    Detail columns are saved as Python dict repr strings inside the CSV (pandas
    stringifies dict/None columns on to_csv). Parse them back safely — if a cell
    isn't a valid dict literal (e.g. truly missing), return an empty dict rather
    than crashing the whole report over one bad cell.
    """
    if pd.isna(value):
        return {}
    if isinstance(value, dict):
        return value
    try:
        parsed = ast.literal_eval(str(value))
        return parsed if isinstance(parsed, dict) else {}
    except (ValueError, SyntaxError):
        return {}


def format_candidate(row: pd.Series) -> str:
    lines = [f"## {row['ticker']} — {row.get('sector', 'unknown sector')}"]
    lines.append(f"- Current price: {row.get('current_price', 'N/A')}")
    lines.append(f"- Total votes: {row.get('total_buy_votes', 0)} buy / {row.get('total_sell_votes', 0)} sell")
    lines.append(f"- Technical group net vote: {row.get('technical_net_vote', 'N/A')}")
    lines.append(f"- Quantitative group net vote: {row.get('quantitative_net_vote', 'N/A')}")
    lines.append(f"- Astrological group status: {row.get('astrological_status', 'N/A')}")
    lines.append(f"- TS context: {row.get('ts_context', 'N/A')}")

    astro_details = safe_parse_dict(row.get("astrological_details"))
    if astro_details:
        lines.append(f"- Astrological detail: {astro_details}")

    return "\n".join(lines)


def main() -> None:
    if not INPUT_CSV.exists():
        raise FileNotFoundError(
            f"{INPUT_CSV} not found — run committee_signals.py or "
            f"screen_top_performers.py first."
        )

    df = pd.read_csv(INPUT_CSV)
    if df.empty:
        print("committee_candidates.csv is empty — no candidates to report on this run.")
        return

    sections = [format_candidate(row) for _, row in df.iterrows()]
    report = (
        f"# Committee Candidates Report\n\n"
        f"{len(df)} candidate(s) found.\n\n"
        + "\n\n".join(sections)
        + "\n\n---\nGenerated by format_report.py — for manual review, not an order."
    )

    OUTPUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_MD.write_text(report, encoding="utf-8")
    print(f"Saved formatted report to: {OUTPUT_MD.resolve()}")
    print("\nUpload this file back to Claude in chat to get a narrative analysis.")


if __name__ == "__main__":
    main()
